/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.obskc.niop.bazapodataka;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Start extends javax.swing.JFrame {
    
    public static final User USER = new User();

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        
        // deklaracija i inicijalizacija svih dostupnih panela
        WelcomePanel welcomePanel = new WelcomePanel();
        LoginPanel loginPanel = new LoginPanel();
        RegisterPanel registerPanel = new RegisterPanel();
        SubmitEssayPanel submitEssayPanel = new SubmitEssayPanel();
        ListEssaysPanel listEssaysPanel = new ListEssaysPanel();
        
        // dodavanje svih panela u main container
        mainContainer.add(welcomePanel, "welcomePanel");
        mainContainer.add(loginPanel, "loginPanel");
        mainContainer.add(registerPanel, "registerPanel");
        mainContainer.add(submitEssayPanel, "submitEssayPanel");
        mainContainer.add(listEssaysPanel, "listEssaysPanel");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();
        topMenuBar = new javax.swing.JMenuBar();
        userMenu = new javax.swing.JMenu();
        registerMenuItem = new javax.swing.JMenuItem();
        loginMenuItem = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        submitEssayMenuItem = new javax.swing.JMenuItem();
        listSubmissionsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));

        mainContainer.setLayout(new java.awt.CardLayout());

        userMenu.setText("Korisnik");

        registerMenuItem.setText("Registracija");
        registerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(registerMenuItem);

        loginMenuItem.setText("Prijava");
        loginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuItemActionPerformed(evt);
            }
        });
        userMenu.add(loginMenuItem);

        topMenuBar.add(userMenu);

        optionsMenu.setText("Mogućnosti");

        submitEssayMenuItem.setText("Prijava završnog rada");
        submitEssayMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEssayMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(submitEssayMenuItem);

        listSubmissionsMenuItem.setText("Prikaz prijava");
        listSubmissionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSubmissionsMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(listSubmissionsMenuItem);

        topMenuBar.add(optionsMenu);

        setJMenuBar(topMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMenuItemActionPerformed
        CardLayout cardLayout = (CardLayout) mainContainer.getLayout();
        cardLayout.show(mainContainer, "registerPanel");
        mainContainer.revalidate();
        mainContainer.repaint();
    }//GEN-LAST:event_registerMenuItemActionPerformed

    private void loginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuItemActionPerformed
        CardLayout cardLayout = (CardLayout) mainContainer.getLayout();
        cardLayout.show(mainContainer, "loginPanel");
        mainContainer.revalidate();
        mainContainer.repaint();
    }//GEN-LAST:event_loginMenuItemActionPerformed

    private void submitEssayMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEssayMenuItemActionPerformed
        User user = Start.USER;
        if (!user.isAuthenticated()) {
            JOptionPane.showMessageDialog(this, "Morate se prijaviti u sustav da pregledali završne radove.", "Greška prijave", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CardLayout cardLayout = (CardLayout) mainContainer.getLayout();
        cardLayout.show(mainContainer, "submitEssayPanel");
        mainContainer.revalidate();
        mainContainer.repaint();
    }//GEN-LAST:event_submitEssayMenuItemActionPerformed

    private void listSubmissionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSubmissionsMenuItemActionPerformed
        User user = Start.USER;
        if (!user.isAuthenticated()) {
            JOptionPane.showMessageDialog(this, "Morate se prijaviti u sustav da pregledali završne radove.", "Greška prijave", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        CardLayout cardLayout = (CardLayout) mainContainer.getLayout();
        cardLayout.show(mainContainer, "listEssaysPanel");
        mainContainer.revalidate();
        mainContainer.repaint();
    }//GEN-LAST:event_listSubmissionsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem listSubmissionsMenuItem;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem registerMenuItem;
    private javax.swing.JMenuItem submitEssayMenuItem;
    private javax.swing.JMenuBar topMenuBar;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables
}
